f1 = open('C:/Users/WilsonXin/Desktop/wilson/001.jpg', 'rb')
f2 = open('C:/Users/WilsonXin/Desktop/wilson/002.jpg', 'rb')
f3 = open('C:/Users/WilsonXin/Desktop/wilson/003.jpg', 'rb')
f4 = open('C:/Users/WilsonXin/Desktop/wilson/004.jpg', 'rb')
f5 = open('C:/Users/WilsonXin/Desktop/wilson/005.jpg', 'rb')
f6 = open('C:/Users/WilsonXin/Desktop/wilson/006.jpg', 'rb')
f7 = open('C:/Users/WilsonXin/Desktop/wilson/007.jpg', 'rb')
f8 = open('C:/Users/WilsonXin/Desktop/wilson/008.jpg', 'rb')
f9 = open('C:/Users/WilsonXin/Desktop/wilson/009.jpg', 'rb')
file_f1 = {'file': ('cache.jpg', f1, 'multipart/form-data', {})}
file_f2 = {'file': ('cache.jpg', f2, 'multipart/form-data', {})}
file_f3 = {'file': ('cache.jpg', f3, 'multipart/form-data', {})}
file_f4 = {'file': ('cache.jpg', f4, 'multipart/form-data', {})}
file_f5 = {'file': ('cache.jpg', f5, 'multipart/form-data', {})}
file_f6 = {'file': ('cache.jpg', f6, 'multipart/form-data', {})}
file_f7 = {'file': ('cache.jpg', f7, 'multipart/form-data', {})}
file_f8 = {'file': ('cache.jpg', f8, 'multipart/form-data', {})}
file_f9 = {'file': ('cache.jpg', f9, 'multipart/form-data', {})}
